I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 108, in script
    call screen TESTLOCATIONS1
ScriptError: could not find label 'TESTLOCATIONSEND'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "game/script.rpy", line 108, in script
    call screen TESTLOCATIONS1
  File "C:\Users\Tony\Desktop\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'TESTLOCATIONSEND'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Space Breakers 0.1
Sat Mar 11 14:24:42 2023
